### PR TITLE
Some comments, tests, and style edits for the LookerUp strategies

### PR DESCRIPTION
**Pull request by marcharper**
Lots of tests, the requests from the PR on the mainline branch, some various style edits of my own. No logic changes, please review the changes for correctness.

We're all excited to merge this strategy in, it's excellent work!

### CODE REVIEW

**Comment by drvinceknight** [comment]
@marcharper in the PR on @mojones's repo I noticed you didn't include a docstring with a table with m,n > 1 ? Do you not think that's worth it? Just an incomplete table in the doctstring to show what it should look like?
I'm thinking something like:

```
+    {
+        ...
+        ('CC', 'DC', 'DD') : D,
+        ('CC', 'DD', 'DD') : D,
+        ('CD', 'DC', 'DC') : C,
+        ('CD', 'DD', 'DC') : C,
+        ...
     }
```

Note that also clarifies that the 2nd and 3rd elements of the tuple need to be strings (or don't they?) I noticed you changed that at this line: https://github.com/mojones/Axelrod/pull/1/files#diff-fb5e6cb7dd44d9816703418407dde658R48 and this line: https://github.com/mojones/Axelrod/pull/1/files#diff-bc67794ae60ba2a40cfaa3ff03577322R67

**Comment by drvinceknight** [comment]
(I think that using the action instances in the tuple keys is a bit confusing if and when it comes to using strings to denote the cases when m > 1)

**Comment by drvinceknight** [comment]
A part from this minor issue, assuming @mojones is happy, once merged in I'm happy for the PR on the main repo to go in :)

**Comment by mojones** [comment]
Excellent work, many thanks.

**Pull request merged**
